console.log("Tests passed! (cause we have none)")
process.exit(0)